import FaceDetectionBlock from "@/component/face-detection-block";
import OverlayImage from "@/component/overlay-image";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Suitizen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FaceDetectionBlock />
      <OverlayImage />
    </>
  );
}
