import Dapp from "@/component/dapp";
import Main from "@/component/main";
import Proposal from "@/component/proposal";
import { refreshInteractionData } from "@/sui-api";
import Head from "next/head";
import { Dispatch, SetStateAction, useEffect } from "react";

function Home({
  path,
  setPath,
}: {
  path: string;
  setPath: Dispatch<SetStateAction<string>>;
}) {
  useEffect(() => {
    refreshInteractionData();
  }, []);
  return (
    <>
      <Head>
        <title>Suitizen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {path === "/" && <Main setPath={setPath} />}
      {path === "/app" && <Dapp setPath={setPath} />}
      {path === "/community" && <Proposal setPath={setPath} />}
    </>
  );
}
Home.noWallet = true;

export default Home;
